# Generated by Django 5.2.4 on 2025-07-26 02:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('data_criacao', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Criação/Matrícula')),
            ],
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(verbose_name='Data e Horário')),
                ('status', models.CharField(choices=[('Agendada', 'Agendada'), ('Realizada', 'Realizada'), ('Cancelada', 'Cancelada'), ('Aluno Ausente', 'Aluno Ausente')], default='Agendada', max_length=20)),
                ('alunos', models.ManyToManyField(blank=True, related_name='aulas', to='scheduling.aluno')),
                ('professores', models.ManyToManyField(blank=True, limit_choices_to={'tipo__in': ['admin', 'professor']}, related_name='aulas', to=settings.AUTH_USER_MODEL)),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aulas', to='scheduling.modalidade')),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo_teorico', models.TextField(blank=True, null=True, verbose_name='Conteúdo Teórico Abordado')),
                ('observacoes_teoria', models.TextField(blank=True, null=True, verbose_name='Observações sobre a Teoria')),
                ('repertorio_musicas', models.TextField(blank=True, null=True, verbose_name='Músicas do Repertório')),
                ('observacoes_repertorio', models.TextField(blank=True, null=True, verbose_name='Observações sobre o Repertório')),
                ('observacoes_gerais', models.TextField(blank=True, null=True, verbose_name='Observações Gerais sobre a Aula')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('aula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relatorio', to='scheduling.aula')),
                ('professor_que_validou', models.ForeignKey(blank=True, limit_choices_to={'tipo__in': ['admin', 'professor']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatorios_validados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemVirada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Exercício')),
                ('bpm', models.CharField(blank=True, max_length=50, null=True, verbose_name='Clique/BPM')),
                ('duracao_min', models.IntegerField(blank=True, null=True, verbose_name='Duração (min)')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_viradas', to='scheduling.relatorioaula')),
            ],
        ),
        migrations.CreateModel(
            name='ItemRudimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Exercício')),
                ('bpm', models.CharField(blank=True, max_length=50, null=True, verbose_name='BPM')),
                ('duracao_min', models.IntegerField(blank=True, null=True, verbose_name='Duração (min)')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_rudimentos', to='scheduling.relatorioaula')),
            ],
        ),
        migrations.CreateModel(
            name='ItemRitmo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Exercício')),
                ('livro_metodo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Livro/Método')),
                ('bpm', models.CharField(blank=True, max_length=50, null=True, verbose_name='Clique/BPM')),
                ('duracao_min', models.IntegerField(blank=True, null=True, verbose_name='Duração (min)')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_ritmo', to='scheduling.relatorioaula')),
            ],
        ),
        migrations.CreateModel(
            name='PresencaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente')], default='presente', max_length=10)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='scheduling.aluno')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas_alunos', to='scheduling.aula')),
            ],
            options={
                'unique_together': {('aula', 'aluno')},
            },
        ),
        migrations.CreateModel(
            name='PresencaProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente')], default='presente', max_length=10)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas_professores', to='scheduling.aula')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('aula', 'professor')},
            },
        ),
    ]
