# Generated by Django 5.2.4 on 2025-07-26 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(verbose_name='Data e Horário')),
                ('status', models.CharField(choices=[('Agendada', 'Agendada'), ('Realizada', 'Realizada'), ('Cancelada', 'Cancelada'), ('Aluno Ausente', 'Aluno Ausente')], default='Agendada', max_length=20)),
                ('alunos', models.ManyToManyField(blank=True, related_name='aulas', to='scheduling.aluno')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aulas', to='scheduling.modalidade')),
                ('professores', models.ManyToManyField(blank=True, limit_choices_to={'tipo__in': ['admin', 'professor']}, related_name='aulas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
