# Generated by Django 5.2.4 on 2025-07-26 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_aula'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PresencaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente')], default='presente', max_length=10)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='scheduling.aluno')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas_alunos', to='scheduling.aula')),
            ],
            options={
                'unique_together': {('aula', 'aluno')},
            },
        ),
        migrations.CreateModel(
            name='PresencaProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente')], default='presente', max_length=10)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas_professores', to='scheduling.aula')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('aula', 'professor')},
            },
        ),
    ]
